apiVersion: #<string>
kind: #<string>
metadata: #<ObjectMeta>
  annotations: #<map[string]string>
  creationTimestamp: #<string>
  deletionGracePeriodSeconds: #<integer>
  deletionTimestamp: #<string>
  finalizers: #<[]string>
  generateName: #<string>
  generation: #<integer>
  labels: #<map[string]string>
  managedFields: #<[]ManagedFieldsEntry>
    apiVersion: #<string>
    fieldsType: #<string>
    fieldsV1: #<FieldsV1>
    manager: #<string>
    operation: #<string>
    subresource: #<string>
    time: #<string>
  name: #<string>
  namespace: #<string>
  ownerReferences: #<[]OwnerReference>
    apiVersion: #<string> -required-
    blockOwnerDeletion: #<boolean>
    controller: #<boolean>
    kind: #<string> -required-
    name: #<string> -required-
    uid: #<string> -required-
  resourceVersion: #<string>
  selfLink: #<string>
  uid: #<string>
spec: #<CertificateSigningRequestSpec> -required-
  expirationSeconds: #<integer>
  extra: #<map[string][]string>
  groups: #<[]string>
  request: #<string> -required-
  signerName: #<string> -required-
  uid: #<string>
  usages: #<[]string>
  username: #<string>
status: #<CertificateSigningRequestStatus>
  certificate: #<string>
  conditions: #<[]CertificateSigningRequestCondition>
    lastTransitionTime: #<string>
    lastUpdateTime: #<string>
    message: #<string>
    reason: #<string>
    status: #<string> -required-
    type: #<string> -required-
